- name: Play level variables
  hosts: local
  connection: local
  vars:
    COURSE: ansible
    DURATION: 10Hrs
  tasks:
  - name: print course information
    ansible.builtin.debug:
    ##Vars reference should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}"

  - name: print course information again
    ansible.builtin.debug:
    ##Vars reference should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}"