- name: variables from files
  hosts: local
  connection: local
  tasks:
    - name: print cousre information
      ansible.builtin.debug:
        msg: "Hello, I'm learning {{ COURSE }}, Duration is {{ DURATION}}"