- name: Varibles from inventory ##Here we learning Host level variables
  hosts: frontend
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello, I'm learning {{ COURSE }} and the duration is {{ DURATION }}"