- name: Varibles from Command line ##Here we learning Hcommand line variables
  hosts: frontend
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello, I'm learning {{ COURSE }} and the duration is {{ DURATION }}"