- name: understanding the preference of variables
  hosts: local
  connection: local
  vars:
    GREETING: "Hello from PLAY"
  vars_files:
    - Course.yaml
  vars_prompt:
  - name: GREETING
    prompt: "Please enter the GREETINGS"
    private: false
  tasks:
  - name: print the GREETING
    vars:
      GREETING: "Hello from task"
    ansible.builtin.debug:
      msg: "{{ GREETING }}"



# 1. command line or args
# 2. Task
# 3. File
# 4. prompt
# 5. Play
# 6. inventory