- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"
  tasks:
  - name: check undefined variables
    ansible.builtin.debug:
      msg: "Hello, {{ persons | default('Arun') }}"

  - name: print name with split
    ansible.builtin.debug:
      msg: "hello {{ persons | split(',') }} "

  - name: convert map into list
     vars:
      course:
        name: ansible
        duration: 10HR
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"