- name: creating Ec2 and route-53 records
  hosts: local
  connection: local
  vars:
    instances:
    - mysql
    - backend
    - frontend
    subnet_id: subnet-05428c3f77f8cd116
    sg_id: sg-0c60287f2f9191e36
    zone: arunkumarnelluri.site
  tasks:
  - name: create Ec2
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t2.micro
      security_group: "{{ sg_id }}"
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
